local-server:
  id: e94c373e-5d26-11ed-9b6a-0242ac120002
  password: ENC(SJiiNjl5qoduOrJwQoL6RECEn7FkM/oI)

push: # time between sending alert messages
  level-exceeded:
    pm1: 60
    pm25: 60
    pm10: 60
    co2: 30
  detection:
    motion: 5

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(/UQrmWAJ/BKXCGGogAgl/A==)
    username: ENC(/UQrmWAJ/BKXCGGogAgl/A==)
    embedded-database-connection: h2
    url: "jdbc:h2:./db/data;INIT=RUNSCRIPT FROM 'classpath:create.sql';"

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/ssl_rootca.p12
    key-alias: iot-assistant-rest
    key-store-password: ENC(SJiiNjl5qoduOrJwQoL6RECEn7FkM/oI)