local-server:
  id: e94c373e-5d26-11ed-9b6a-0242ac120002
  fcm-key: ENC(ZLdk6wIBtQ9vd1RIrvAoVOkZN3N3eWeDE3uXGzqm6UjZkQFSvS7w2emEWc73wSR01rRI92p1B1zsbXUucBgBiEYE0JJlBAoZS9g5bRC6FCVb9bKNOrjqcqm0Wgh/yrF7H0pBLKU/Bx6MjJY80IKuRhZSoi/z1M2dhJmaAOFbIgVcE9wWdO8AjlrNh3g1p8YrmG7QG4XPoddjpsKPDOm2+KK23A8xs7yB)
  #password: ENC(SJiiNjl5qoduOrJwQoL6RECEn7FkM/oI)

push: # time between sending alert messages
  level-exceeded:
    pm1: 60
    pm25: 60
    pm10: 60
    co2: 30
  detection:
    motion: 5

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(/UQrmWAJ/BKXCGGogAgl/A==)
    username: ENC(/UQrmWAJ/BKXCGGogAgl/A==)
    embedded-database-connection: h2
    url: "jdbc:h2:./db/data;INIT=RUNSCRIPT FROM 'classpath:create.sql';"